// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Common;

public sealed class LoanRiskDetailRow
{
    public Guid LoanId { get; set; }
    public Guid CustomerId { get; set; }
    public string? CustomerName { get; set; }
    public decimal CurrentBalance { get; set; }
    public decimal EstimatedProvision { get; set; }
    public int DaysOverdue { get; set; }
    public string? RiskCategory { get; set; }
}
