// <auto-generated>
// Generado a partir de openapi_crm.txt (OpenAPI 3.0.1, "Crm.WebApi"),
// esquema PricingBandDto. No editar valores/nombres de propiedades a mano
// sin volver a sincronizar contra el swagger real si este cambia.
// </auto-generated>

namespace CreditSystem.Frontend.Web.Models.Common;

/// <summary>
/// Banda de precio (rango de score -> tasa de interes / monto maximo). El
/// shape es identico en las 3 direcciones del swagger CRM en las que
/// aparece (CreateRiskMatrixDto, UpdateRiskMatrixDto, RiskMatrixDetailDto),
/// por eso se modela una sola vez aqui en vez de duplicarlo en Requests y
/// Responses.
/// </summary>
public sealed class PricingBand
{
    public decimal MinScore { get; set; }
    public decimal MaxScore { get; set; }
    public decimal InterestRate { get; set; }
    public decimal MaxAmount { get; set; }
}
