// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// Los 5 campos base coinciden exactamente con el schema "ProblemDetails"
// del swagger. El campo "Errors" NO esta en ese schema (el swagger solo
// documenta el ProblemDetails base), pero se agrega manualmente porque
// ASP.NET Core serializa los errores de validacion (400 de FluentValidation)
// como ValidationProblemDetails, que extiende ProblemDetails con un
// diccionario "errors" — patron estandar del framework. Si el backend real
// no lo envia, simplemente queda null y no afecta nada.
// </auto-generated>

namespace CreditSystem.Frontend.Web.Models.Common;

public sealed class ProblemDetails
{
    public string? Type { get; set; }
    public string? Title { get; set; }
    public int? Status { get; set; }
    public string? Detail { get; set; }
    public string? Instance { get; set; }
    public Dictionary<string, string[]>? Errors { get; set; }
}
