// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Common;

public sealed class RiskCategoryRow
{
    public string? Category { get; set; }
    public decimal ProvisionPercentage { get; set; }
    public int LoanCount { get; set; }
    public decimal TotalBalance { get; set; }
    public decimal TotalProvision { get; set; }
}
