// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using System.Collections.Generic;

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Common;

public sealed class RuleEvaluationResult
{
    public bool Passed { get; set; }
    public string? RuleName { get; set; }
    public string? Message { get; set; }
    public Dictionary<string, object>? Metadata { get; set; }
}
