// <auto-generated>
// Grupo "Loan Contracts": endpoint agregado al backend despues del ultimo
// open_api.json sincronizado (54 rutas). Shape tomado directamente de
// CreditSystem.Api/EndPoints/LoanContractEndpoints.cs +
// CreditSystem.Application/Commands/ConfirmDisbursement/ConfirmDisbursementCommand.cs.
// Resincronizar contra el swagger real cuando se regenere open_api.json.
// </auto-generated>

namespace CreditSystem.Frontend.Web.Models.Requests;

public sealed class ConfirmDisbursementRequest
{
    public string? ConfirmedBy { get; set; }
}
