// <auto-generated>
// Generado a partir de openapi_crm.txt (OpenAPI 3.0.1, "Crm.WebApi"),
// esquema CreateRiskRuleDto. No editar valores/nombres de propiedades a
// mano sin volver a sincronizar contra el swagger real si este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Requests;

public sealed class CreateRiskRuleRequest
{
    public string? Name { get; set; }
    public RiskRuleType RuleType { get; set; }
    public RiskRuleTargetField TargetField { get; set; }
    public Dictionary<string, string>? Parameters { get; set; }
    public double Weight { get; set; }
}
