// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Requests;

public sealed class CreateCreditLineRequest
{
    public Guid ExternalCustomerId { get; set; }
    public decimal CreditLimit { get; set; }
    public string? Currency { get; set; }
    public decimal? InterestRate { get; set; }
    public decimal? MinimumPaymentPercentage { get; set; }
    public decimal? MinimumPaymentAmount { get; set; }
    public int? BillingCycleDay { get; set; }
    public int? GracePeriodDays { get; set; }
}
