// <auto-generated>
// Generado a partir de openapi_crm.txt (OpenAPI 3.0.1, "Crm.WebApi"),
// esquema CreateRiskMatrixDto. No editar valores/nombres de propiedades a
// mano sin volver a sincronizar contra el swagger real si este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Common;

namespace CreditSystem.Frontend.Web.Models.Requests;

public sealed class CreateRiskMatrixRequest
{
    public string? Name { get; set; }
    public double AutoApproveThreshold { get; set; }
    public double AutoRejectThreshold { get; set; }
    public List<Guid>? RuleIds { get; set; }
    public List<PricingBand>? PricingBands { get; set; }
}
