// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using System.Collections.Generic;

using CreditSystem.Frontend.Web.Models.Common;
using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Requests;

public sealed class CreateContractCommand
{
    public Guid ExternalCustomerId { get; set; }
    public Guid ProductId { get; set; }
    public decimal Amount { get; set; }
    public string? Currency { get; set; }
    public int TermMonths { get; set; }
    public List<GuaranteeInput>? Guarantees { get; set; }
    public AmortizationMethod AmortizationMethod { get; set; }
    public string? RateType { get; set; }
    public decimal? Spread { get; set; }
    public string? ReferenceRateId { get; set; }
}
