// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using System.Collections.Generic;

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Requests;

public sealed class CreateProductRequest
{
    public string? Name { get; set; }
    public decimal MinAmount { get; set; }
    public decimal MaxAmount { get; set; }
    public int MinTermMonths { get; set; }
    public int MaxTermMonths { get; set; }
    public decimal? BaseInterestRate { get; set; }
    public decimal? MaxLtv { get; set; }
    public AmortizationMethod DefaultAmortizationMethod { get; set; }
    public bool RequiresCollateral { get; set; }
    public List<WaterfallStepRequest>? Waterfall { get; set; }
    public SocialCapitalConfigRequest SocialCapitalConfig { get; set; } = new();
}
