// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Requests;

public sealed class CreateGuaranteeRequest
{
    public GuaranteeType Type { get; set; }
    public string? Description { get; set; }
    public decimal AppraisalValue { get; set; }
    public decimal CoverageRate { get; set; }
    public DateOnly? ExpirationDate { get; set; }
}
