// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Requests;

public sealed class RestructureContractRequest
{
    public decimal NewInterestRate { get; set; }
    public int NewTermMonths { get; set; }
    public decimal? ForgiveAmount { get; set; }
    public string? Reason { get; set; }
}
