// <auto-generated>
// Generado a partir de openapi_crm.txt (OpenAPI 3.0.1, "Crm.WebApi"),
// esquema TriggerRiskEvaluationDto. No editar valores/nombres de
// propiedades a mano sin volver a sincronizar contra el swagger real si
// este cambia.
// </auto-generated>

namespace CreditSystem.Frontend.Web.Models.Requests;

public sealed class TriggerRiskEvaluationRequest
{
    public Guid CreditApplicationId { get; set; }
}
