// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using System.Collections.Generic;

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class ChangeCreditLimitResponse
{
    public bool Success { get; set; }
    public Guid? CreditLineId { get; set; }
    public decimal? PreviousLimit { get; set; }
    public decimal? NewLimit { get; set; }
    public decimal? AvailableCredit { get; set; }
    public string? Message { get; set; }
    public List<string>? Errors { get; set; }
}
