// <auto-generated>
// Grupo "Loan Contracts": endpoint agregado al backend despues del ultimo
// open_api.json sincronizado (54 rutas). Shape tomado directamente de
// CreditSystem.Application/Commands/ConfirmDisbursement/ConfirmDisbursementResponse.cs.
// Resincronizar contra el swagger real cuando se regenere open_api.json.
// </auto-generated>

using System.Collections.Generic;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class ConfirmDisbursementResponse
{
    public bool Success { get; set; }
    public Guid? LoanId { get; set; }
    public string? ConfirmedBy { get; set; }
    public DateTime? DisbursedAt { get; set; }
    public string? Message { get; set; }
    public List<string>? Errors { get; set; }
}
