// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using System.Collections.Generic;

using CreditSystem.Frontend.Web.Models.Common;
using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class CreateContractResponse
{
    public bool Success { get; set; }
    public Guid? ContractId { get; set; }
    public string? Message { get; set; }
    public decimal? ApprovedRate { get; set; }
    public List<RuleEvaluationResult>? EvaluationResults { get; set; }
    public List<string>? Errors { get; set; }
}
