// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class DelinquentLoanResponse
{
    public Guid LoanId { get; set; }
    public Guid CustomerId { get; set; }
    public string? CustomerName { get; set; }
    public string? CustomerPhone { get; set; }
    public string? CustomerEmail { get; set; }
    public decimal Principal { get; set; }
    public decimal CurrentBalance { get; set; }
    public decimal TotalOwed { get; set; }
    public int DaysOverdue { get; set; }
    public int PaymentsMissed { get; set; }
    public DateTime? LastPaymentAt { get; set; }
    public DateTime? NextActionDate { get; set; }
    public string? CollectionStatus { get; set; }
    public string? AssignedCollector { get; set; }
}
