// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class MemberSharesResponse
{
    public Guid ExternalId { get; set; }
    public decimal TotalSharesAmount { get; set; }
    public string? SharesCurrency { get; set; }
    public int NumberOfContributions { get; set; }
    public DateTime? LastContributionDate { get; set; }
}
