// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class PaidOffLoanResponse
{
    public Guid LoanId { get; set; }
    public Guid CustomerId { get; set; }
    public string? CustomerName { get; set; }
    public decimal Principal { get; set; }
    public decimal TotalInterestPaid { get; set; }
    public decimal TotalFeesPaid { get; set; }
    public int PaymentsMade { get; set; }
    public int OriginalTermMonths { get; set; }
    public bool EarlyPayoff { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime PaidOffAt { get; set; }
    public int DaysToPayoff { get; set; }
}
