// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class PaymentStatusResponse
{
    public Guid PaymentId { get; set; }
    public Guid? LoanId { get; set; }
    public Guid? CreditLineId { get; set; }
    public Guid CustomerId { get; set; }
    public decimal Amount { get; set; }
    public string? Currency { get; set; }
    public string? PaymentMethod { get; set; }
    public string? Status { get; set; }
    public DateTime AcceptedAt { get; set; }
    public DateTime? ProcessedAt { get; set; }
    public decimal? PrincipalPaid { get; set; }
    public decimal? InterestPaid { get; set; }
    public decimal? FeesPaid { get; set; }
    public decimal? NewBalance { get; set; }
    public decimal? NewAvailableCredit { get; set; }
    public bool? IsPaidOff { get; set; }
    public string? ErrorCode { get; set; }
    public string? ErrorMessage { get; set; }
}
