// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using System.Collections.Generic;

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class PayoffContractResponse
{
    public bool Success { get; set; }
    public Guid? LoanId { get; set; }
    public Guid? PaymentId { get; set; }
    public decimal? PayoffAmount { get; set; }
    public decimal? PrincipalPaid { get; set; }
    public decimal? InterestPaid { get; set; }
    public decimal? FeesPaid { get; set; }
    public decimal? TotalPrincipalPaid { get; set; }
    public decimal? TotalInterestPaid { get; set; }
    public decimal? TotalFeesPaid { get; set; }
    public bool? EarlyPayoff { get; set; }
    public DateTime? PaidOffAt { get; set; }
    public string? Message { get; set; }
    public List<string>? Errors { get; set; }
}
