// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class PayoffAmountResponse
{
    public Guid LoanId { get; set; }
    public decimal PrincipalBalance { get; set; }
    public decimal AccruedInterest { get; set; }
    public decimal PendingFees { get; set; }
    public decimal TotalPayoffAmount { get; set; }
    public DateTime CalculatedAsOf { get; set; }
    public DateTime ValidUntil { get; set; }
    public string? Currency { get; set; }
}
