// <auto-generated>
// Grupo "Loan Contracts": endpoint agregado al backend despues del ultimo
// open_api.json sincronizado (54 rutas). Shape tomado directamente de
// CreditSystem.Api/EndPoints/Dtos/DisbursementDtos.cs (PendingDisbursementResponse).
// Resincronizar contra el swagger real cuando se regenere open_api.json.
// </auto-generated>

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class PendingDisbursementResponse
{
    public Guid LoanId { get; set; }
    public Guid CustomerId { get; set; }
    public string? CustomerName { get; set; }
    public decimal Principal { get; set; }
    public string? Currency { get; set; }
    public string? DisbursementMethod { get; set; }
    public string? DestinationAccount { get; set; }
    public DateTime ApprovedAt { get; set; }
    public DateTime? DisbursementInstructedAt { get; set; }
    public string? Status { get; set; }
    public DateTime UpdatedAt { get; set; }
}
