// <auto-generated>
// Grupo "ProjectionAdmin": endpoint agregado al backend despues del ultimo
// open_api.json sincronizado (54 rutas). Shape tomado directamente de
// CreditSystem.Api/EndPoints/ProjectionAdminEndpoints.cs (ProjectionFailureResponse).
// Resincronizar contra el swagger real cuando se regenere open_api.json.
// </auto-generated>

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class ProjectionFailureResponse
{
    public Guid Id { get; set; }
    public Guid EventId { get; set; }
    public Guid StreamId { get; set; }
    public string? EventType { get; set; }
    public string? ProjectorName { get; set; }
    public string? ErrorMessage { get; set; }
    public DateTime OccurredAt { get; set; }
    public int Attempts { get; set; }
    public bool Resolved { get; set; }
    public DateTime? ResolvedAt { get; set; }
}
