// <auto-generated>
// Grupo "ProjectionAdmin": endpoint agregado al backend despues del ultimo
// open_api.json sincronizado (54 rutas). Shape tomado directamente de
// CreditSystem.Api/EndPoints/ProjectionAdminEndpoints.cs (RebuildProjections,
// respuesta anonima `{ Message, Projectors }` con status 202 Accepted).
// Resincronizar contra el swagger real cuando se regenere open_api.json.
// </auto-generated>

using System.Collections.Generic;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class RebuildProjectionsResponse
{
    public string? Message { get; set; }
    public List<string>? Projectors { get; set; }
}
