// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class ReferenceRateResponse
{
    public string? Id { get; set; }
    public string? Name { get; set; }
    public decimal CurrentValue { get; set; }
    public DateTime EffectiveDate { get; set; }
    public string? Source { get; set; }
    public DateTime UpdatedAt { get; set; }
}
