// <auto-generated>
// Grupo "ProjectionAdmin": endpoint agregado al backend despues del ultimo
// open_api.json sincronizado (54 rutas). Shape tomado directamente de
// CreditSystem.Api/EndPoints/ProjectionAdminEndpoints.cs (ResolveFailure,
// respuesta anonima `{ Id, Resolved }`).
// Resincronizar contra el swagger real cuando se regenere open_api.json.
// </auto-generated>

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class ResolveProjectionFailureResponse
{
    public Guid Id { get; set; }
    public bool Resolved { get; set; }
}
