// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using System.Collections.Generic;

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class RestructureContractResponse
{
    public bool Success { get; set; }
    public Guid? LoanId { get; set; }
    public decimal? PreviousRate { get; set; }
    public decimal? NewRate { get; set; }
    public int? PreviousTermMonths { get; set; }
    public int? NewTermMonths { get; set; }
    public decimal? AmountForgiven { get; set; }
    public decimal? NewBalance { get; set; }
    public decimal? NewMonthlyPayment { get; set; }
    public string? Message { get; set; }
    public List<string>? Errors { get; set; }
}
