// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class RevolvingPaymentAcceptedResponse
{
    public bool IsAccepted { get; set; }
    public Guid? PaymentId { get; set; }
    public Guid? CreditLineId { get; set; }
    public string? Status { get; set; }
    public string? TrackingUrl { get; set; }
    public DateTime? AcceptedAt { get; set; }
    public string? ErrorMessage { get; set; }
}
