// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class RevolvingCreditSummaryResponse
{
    public Guid CreditLineId { get; set; }
    public Guid CustomerId { get; set; }
    public string? CustomerName { get; set; }
    public string? Status { get; set; }
    public decimal CreditLimit { get; set; }
    public decimal CurrentBalance { get; set; }
    public decimal AvailableCredit { get; set; }
    public decimal AccruedInterest { get; set; }
    public decimal PendingFees { get; set; }
    public decimal TotalOwed { get; set; }
    public decimal UtilizationRate { get; set; }
    public decimal InterestRate { get; set; }
    public decimal MinimumPaymentPercentage { get; set; }
    public decimal MinimumPaymentAmount { get; set; }
    public int BillingCycleDay { get; set; }
    public int GracePeriodDays { get; set; }
    public DateTime? ActivatedAt { get; set; }
    public DateTime? NextStatementDate { get; set; }
    public DateTime? PaymentDueDate { get; set; }
    public decimal? CurrentMinimumPayment { get; set; }
    public string? Currency { get; set; }
}
