// <auto-generated>
// Generado a partir de openapi_crm.txt (OpenAPI 3.0.1, "Crm.WebApi"),
// esquema RiskRuleDto. No editar valores/nombres de propiedades a mano sin
// volver a sincronizar contra el swagger real si este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class RiskRuleResponse
{
    public Guid Id { get; set; }
    public string? Name { get; set; }
    public RiskRuleType RuleType { get; set; }
    public RiskRuleTargetField TargetField { get; set; }
    public Dictionary<string, string>? Parameters { get; set; }
    public double Weight { get; set; }
    public DateTime CreatedAt { get; set; }
}
