// <auto-generated>
// Generado a partir de openapi_crm.txt (OpenAPI 3.0.1, "Crm.WebApi"),
// esquema RiskEvaluationDto. No editar valores/nombres de propiedades a
// mano sin volver a sincronizar contra el swagger real si este cambia.
// </auto-generated>

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class RiskEvaluationResponse
{
    public Guid Id { get; set; }
    public Guid CreditApplicationId { get; set; }
    public Guid RiskMatrixId { get; set; }
    public int RiskMatrixVersion { get; set; }
    public double TotalScore { get; set; }
    public string? Outcome { get; set; }
    public double? SuggestedInterestRate { get; set; }
    public double? SuggestedMaxAmount { get; set; }
    public DateTime EvaluatedAt { get; set; }
    public List<ScoreCardEntryResponse>? Entries { get; set; }
}
