// <auto-generated>
// Generado a partir de openapi_crm.txt (OpenAPI 3.0.1, "Crm.WebApi"),
// esquema RiskMatrixRuleDetailDto. No editar valores/nombres de
// propiedades a mano sin volver a sincronizar contra el swagger real si
// este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class RiskMatrixRuleDetailResponse
{
    public Guid RuleId { get; set; }
    public string? RuleName { get; set; }
    public RiskRuleType RuleType { get; set; }
    public RiskRuleTargetField TargetField { get; set; }
    public double Weight { get; set; }
    public int Order { get; set; }
}
