// <auto-generated>
// Generado a partir de openapi_crm.txt (OpenAPI 3.0.1, "Crm.WebApi"),
// esquema RiskMatrixDetailDto. No editar valores/nombres de propiedades a
// mano sin volver a sincronizar contra el swagger real si este cambia.
// </auto-generated>

using CreditSystem.Frontend.Web.Models.Common;
using CreditSystem.Frontend.Web.Models.Enums;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class RiskMatrixDetailResponse
{
    public Guid Id { get; set; }
    public string? Name { get; set; }
    public int Version { get; set; }
    public RiskMatrixStatus Status { get; set; }
    public double AutoApproveThreshold { get; set; }
    public double AutoRejectThreshold { get; set; }
    public DateTime CreatedAt { get; set; }
    public List<RiskMatrixRuleDetailResponse>? Rules { get; set; }
    public List<PricingBand>? PricingBands { get; set; }
}
