// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using System.Collections.Generic;

using CreditSystem.Frontend.Web.Models.Common;

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class RiskSummaryResponse
{
    public List<RiskCategoryRow>? Categories { get; set; }
    public int TotalLoans { get; set; }
    public decimal TotalPortfolioBalance { get; set; }
    public decimal TotalRequiredProvision { get; set; }
}
