// <auto-generated>
// Grupo "Underwriting Policies": endpoint agregado al backend despues del
// ultimo open_api.json sincronizado (54 rutas). Shape tomado directamente
// de CreditSystem.Api/EndPoints/UnderwritingPolicyEndpoints.cs
// (UnderwritingPolicyResponse) + CreditSystem.Domain/Models/UnderwritingPolicy.
// Resincronizar contra el swagger real cuando se regenere open_api.json.
// </auto-generated>

namespace CreditSystem.Frontend.Web.Models.Responses;

public sealed class UnderwritingPolicyResponse
{
    public string? Id { get; set; }
    public decimal BaseInterestRate { get; set; }
    public decimal MaxDtiRatio { get; set; }
    public int SharesMultiplierLimit { get; set; }
    public bool EnforceSharesCapacityLimit { get; set; }
    public bool RequireActiveMembership { get; set; }

    /// <summary>
    /// DOCUMENTACION INSUFICIENTE: el backend serializa el enum de dominio
    /// `NoScoreBehavior` con `.ToString()` (string libre, sin catalogo
    /// publicado); confirmar los valores posibles cuando se documente.
    /// </summary>
    public string? NoScoreBehavior { get; set; }

    public int GracePeriodDays { get; set; }
    public decimal PenaltyRate { get; set; }
    public decimal OriginationFeeRate { get; set; }
    public int AutoDefaultThresholdDays { get; set; }
}
