// <auto-generated>
// Generado a partir de open_api.json (OpenAPI 3.0.1, "Credit System API").
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

namespace CreditSystem.Frontend.Web.Models.Enums;

/// <summary>
/// DOCUMENTACION INSUFICIENTE: el swagger solo expone los valores enteros
/// de PaymentComponent (sin x-enumNames ni descripcion). Los nombres de abajo son una
/// inferencia razonable (documentacion funcional previa / convencion comun)
/// y DEBEN confirmarse contra el enum C# real del backend antes de depender
/// de ellos para logica de negocio. El valor entero SI es el contrato real
/// y no debe modificarse.
/// </summary>
public enum PaymentComponent
{
    Principal = 1,
    Interest = 2,
    Fees = 3,
    Penalty = 4,
    Insurance = 5,
    Other = 6,
}
