// <auto-generated>
// Generado a partir de openapi_crm.txt (OpenAPI 3.0.1, "Crm.WebApi"), tag "RiskEngine".
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using System.Text.Json.Serialization;

namespace CreditSystem.Frontend.Web.Models.Enums;

/// <summary>
/// DOCUMENTACION INSUFICIENTE: el swagger CRM tipa "ruleType" como string
/// libre, sin enum ni catalogo de valores posibles. Los valores de abajo son
/// una inferencia razonable de como un motor de reglas de riesgo suele
/// evaluar un campo objetivo (umbral minimo/maximo, rango, lista de
/// exclusion/inclusion) y DEBEN confirmarse contra el backend real antes de
/// depender de ellos para logica de negocio. Se usa JsonStringEnumConverter
/// porque el campo viaja como string en el wire (a diferencia de enums como
/// GuaranteeType, que viajan como entero).
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum RiskRuleType
{
    MinThreshold,
    MaxThreshold,
    Range,
    Blacklist,
    Whitelist,
}
