// <auto-generated>
// Generado a partir de openapi_crm.txt (OpenAPI 3.0.1, "Crm.WebApi"), tag "RiskEngine".
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using System.Text.Json.Serialization;

namespace CreditSystem.Frontend.Web.Models.Enums;

/// <summary>
/// DOCUMENTACION INSUFICIENTE: el swagger CRM tipa "targetField" como string
/// libre, sin enum ni catalogo de valores posibles. Los valores de abajo son
/// los unicos campos financieros confirmados en DTOs del swagger CRM
/// (UpdateCustomerFinancialsDto.creditScore/monthlyIncome/monthlyDebt,
/// CustomerWorkInfoDto.salary) y DEBEN confirmarse/ampliarse contra el
/// backend real antes de depender de ellos para logica de negocio. Se usa
/// JsonStringEnumConverter porque el campo viaja como string en el wire.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum RiskRuleTargetField
{
    CreditScore,
    MonthlyIncome,
    MonthlyDebt,
    Salary,
}
