// <auto-generated>
// Generado a partir de openapi_crm.txt (OpenAPI 3.0.1, "Crm.WebApi"), tag "RiskEngine".
// No editar valores/nombres de propiedades a mano sin volver a sincronizar
// contra el swagger real si este cambia.
// </auto-generated>

using System.Text.Json.Serialization;

namespace CreditSystem.Frontend.Web.Models.Enums;

/// <summary>
/// DOCUMENTACION INSUFICIENTE: el swagger CRM tipa "status" (de RiskMatrixDto
/// / RiskMatrixDetailDto) como string libre, sin enum ni catalogo de valores
/// posibles. Los valores de abajo se infieren de que existe un endpoint
/// POST /risk-matrices/{id}/activate y un campo "version" (sugiere que solo
/// una version de la matriz esta activa a la vez) y DEBEN confirmarse contra
/// el backend real. Se usa JsonStringEnumConverter porque el campo viaja
/// como string en el wire.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum RiskMatrixStatus
{
    Draft,
    Active,
    Archived,
}
